const notes=[{title:'Semantic Organization MVP',text:'Build a context-aware workspace that groups information by meaning and conceptual relationships.',cat:'Project',cluster:'AI Project',terms:['AI','Semantic','Hackathon']},{title:'Semantic Search Research',text:'Compare approaches for finding related concepts rather than relying only on exact keywords.',cat:'Research',cluster:'AI Project',terms:['Search','Research','Concepts']},{title:'Frontend Architecture',text:'React interface for the semantic workspace with editable defaults and an explainable inspector.',cat:'Project',cluster:'AI Project',terms:['React','Frontend','UI']}];
const notesEl=document.getElementById('notes');
function renderNotes(){notesEl.innerHTML=notes.map((n,i)=>`<article class="note-card" data-index="${i}"><div class="note-top"><span class="tag">${n.cat.toUpperCase()}</span><span>•••</span></div><h4>${n.title}</h4><p>${n.text}</p><div class="meta"><span>Cluster: ${n.cluster}</span>${n.terms.map(t=>`<span>${t}</span>`).join('')}</div></article>`).join('');document.querySelectorAll('.note-card').forEach(c=>c.onclick=()=>selectNote(+c.dataset.index));}
function selectNote(i){const n=notes[i];document.getElementById('stateCategory').textContent=n.cat;document.getElementById('confidence').textContent=(88+i*3)+'%';document.getElementById('chips').innerHTML=n.terms.map(t=>`<button>${t}</button>`).join('');}
renderNotes();
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.getElementById(btn.dataset.view).classList.add('active-view');document.getElementById('pageTitle').textContent=btn.dataset.view==='workspace'?'Organize by meaning, not just folders.':btn.dataset.view==='concepts'?'See how your ideas connect.':'Make semantic defaults work your way.';});
const modal=document.getElementById('modal');document.getElementById('newNote').onclick=()=>modal.classList.add('show');document.getElementById('closeModal').onclick=()=>modal.classList.remove('show');
document.getElementById('addNote').onclick=()=>{const text=document.getElementById('noteText').value.trim();if(!text)return;notes.unshift({title:'New contextual note',text,cat:document.getElementById('categoryDefault').value,cluster:'AI Project',terms:['Context','AI','Semantic']});renderNotes();selectNote(0);modal.classList.remove('show');document.getElementById('noteText').value='';};
document.getElementById('categoryDefault').onchange=e=>document.getElementById('stateCategory').textContent=e.target.value;
document.getElementById('saveDefaults').onclick=e=>{e.target.textContent='Saved ✓';setTimeout(()=>e.target.textContent='Save changes',1200);};
