const notes=[{title:'Semantic Organization MVP',text:'Build a context-aware workspace that groups information by meaning and conceptual relationships.',cat:'Project',priority:'High',cluster:'AI Project',terms:['AI','Semantic','Hackathon'],confidence:94},{title:'Semantic Search Research',text:'Compare approaches for finding related concepts rather than relying only on exact keywords.',cat:'Research',priority:'High',cluster:'Semantic Search',terms:['Search','Research','Concepts'],confidence:91},{title:'Frontend Architecture',text:'React interface for the semantic workspace with editable defaults and an explainable inspector.',cat:'Project',priority:'Medium',cluster:'AI Project',terms:['React','Frontend','UI'],confidence:88}];
const state={category:'Project',priority:'High',cluster:'AI Project',sensitivity:'Balanced',terms:true};
const notesEl=document.getElementById('notes');
function renderNotes(){notesEl.innerHTML=notes.map((n,i)=>`<article class="note-card" data-index="${i}"><div class="note-top"><span class="tag">${n.cat.toUpperCase()}</span><span class="confidence-mini">${n.confidence}%</span></div><h4>${n.title}</h4><p>${n.text}</p><div class="meta"><span>Cluster: ${n.cluster}</span><span>Priority: ${n.priority}</span>${n.terms.map(t=>`<span>${t}</span>`).join('')}</div></article>`).join('');document.querySelectorAll('.note-card').forEach(c=>c.onclick=()=>selectNote(+c.dataset.index));}
function selectNote(i){const n=notes[i];state.category=n.cat;state.priority=n.priority;state.cluster=n.cluster;document.getElementById('confidence').textContent=n.confidence+'%';document.getElementById('chips').innerHTML=n.terms.map(t=>`<button>${t}</button>`).join('');syncInspector(n.confidence,n.terms);}
function syncInspector(conf=92,terms=['AI','Semantic','React','Hackathon','Research']){document.getElementById('stateCategory').textContent=state.category;document.getElementById('statePriority').textContent=state.priority;document.getElementById('stateCluster').textContent=state.cluster;document.getElementById('stateSensitivity').textContent=state.sensitivity;document.getElementById('confidence').textContent=conf+'%';document.getElementById('chips').innerHTML=terms.map(t=>`<button>${t}</button>`).join('');document.getElementById('reasons').innerHTML=`<div><b>Category</b><span>AI + hackathon + app context → Project</span></div><div><b>Priority</b><span>Active build language → ${state.priority}</span></div><div><b>Cluster</b><span>Repeated AI/project terms → ${state.cluster}</span></div><div><b>Relationships</b><span>Concept overlap → ${state.sensitivity}</span></div>`;document.getElementById('traceDefaults').textContent=`${state.category} · ${state.priority} · ${state.cluster}`;}
renderNotes();syncInspector();
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.getElementById(btn.dataset.view).classList.add('active-view');document.getElementById('pageTitle').textContent={workspace:'Organize by meaning, not just folders.',concepts:'See how your ideas connect.',defaults:'Make semantic defaults work your way.',evidence:'Show the reasoning behind every default.'}[btn.dataset.view];});
const modal=document.getElementById('modal');document.getElementById('newNote').onclick=()=>modal.classList.add('show');document.getElementById('closeModal').onclick=()=>modal.classList.remove('show');
document.getElementById('addNote').onclick=()=>{const text=document.getElementById('noteText').value.trim();if(!text)return;const lower=text.toLowerCase();const terms=[];['AI','Semantic','Research','React','Hackathon','Frontend'].forEach(t=>{if(lower.includes(t.toLowerCase()))terms.push(t)});if(!terms.length)terms.push('Context','Concept');notes.unshift({title:'New contextual note',text,cat:state.category,priority:state.priority,cluster:state.cluster,terms,confidence:90});renderNotes();selectNote(0);document.getElementById('activity').innerHTML='<span>NOW</span> New note analyzed; semantic defaults applied and exposed for editing.';modal.classList.remove('show');document.getElementById('noteText').value='';};
function updateState(){state.category=document.getElementById('categoryDefault').value;state.priority=document.getElementById('priorityDefault').value;state.cluster=document.getElementById('clusterDefault').value||'Unclustered';state.sensitivity=document.getElementById('sensitivity').value;state.terms=document.getElementById('termToggle').checked;syncInspector(92);document.getElementById('stateMessage').textContent='Edited values are now the active semantic state. The decision trace reflects your changes.';document.getElementById('activity').innerHTML='<span>NOW</span> User edited semantic defaults; live state updated.';}
['categoryDefault','priorityDefault','clusterDefault','sensitivity','termToggle'].forEach(id=>document.getElementById(id).addEventListener('change',updateState));document.getElementById('clusterDefault').addEventListener('input',updateState);
document.getElementById('resetDefaults').onclick=()=>{document.getElementById('categoryDefault').value='Project';document.getElementById('priorityDefault').value='High';document.getElementById('clusterDefault').value='AI Project';document.getElementById('sensitivity').value='Balanced';document.getElementById('termToggle').checked=true;updateState();};document.getElementById('saveDefaults').onclick=e=>{e.target.textContent='Saved ✓';document.getElementById('activity').innerHTML='<span>NOW</span> Semantic defaults saved as active workspace state.';setTimeout(()=>e.target.textContent='Save changes',1200);};
